### PR TITLE
get rid of git submodules

### PR DESCRIPTION
**Pull request by das-g**
(cleans up after #227)

#### reviewed by:
- [ ] @wasabideveloper
- [ ] @njordan-hsr

### CODE REVIEW

**Comment by wasabideveloper** [comment]
What's the reason for checking in foreign code in our repo and removing the submodule?

**Comment by das-g** [comment]
> What's the reason for checking in foreign code in our repo and removing the submodule?

I guess:

* Simplifying setup for new developers / new clones of the repo
* Simplifying deployment

@njordan-hsr can you comment on that? You've made the changes in #227

**Comment by wasabideveloper** [comment]
I think it's not a good idea to remove the submodules. It's the way, subrepos/foreign code should be handled. For the deployment we use a script and for development setup we can do the same. So it's not necessary to simplify this a little bit by doing something bad on another side.

**Comment by njordan-hsr** [comment]
We used a master checkout from a github repo, which might change at any point in the future. We could've locked it to a certain commit, but in general we don't use it much differently as any other third party javascript code, so I think it makes sense to have all using the same mechanism (checking it into source control and be sure, it is available in the version we want).

**Pull request merged**
