### PR TITLE
display build status of develop branch

### PR DESCRIPTION
**Pull request by das-g**
Reviewed by:
- [x] @wasabideveloper
- [x] @hixi

### CODE REVIEW

**Comment by das-g** [comment]
Should build status of `master` be made visible, too? (Once the changes from #323 have made it to `master` ...)

**Comment by hixi** [comment]
Not sure about master, because we would to correct that link each time we pull develop in to master (ie. make a release).

**Comment by das-g** [comment]
> Not sure about master, because we would to correct that link each time we pull develop in to master (ie. make a release).

Replacing the indicator widget each time is probably not worth the hassle, but we could simply have widgets for both branches in the README, like so:
```markdown
`develop`: [![Build Status](https://travis-ci.org/geometalab/osmaxx.svg?branch=develop)](https://travis-ci.org/geometalab/osmaxx)
`master`: [![Build Status](https://travis-ci.org/geometalab/osmaxx.svg?branch=master)](https://travis-ci.org/geometalab/osmaxx)
```
to produce something like
> `develop`: [Build Status](https://travis-ci.org/geometalab/osmaxx)
> `master`: [Build Status](https://travis-ci.org/geometalab/osmaxx)

**Comment by hixi** [comment]
I like that idea :-)
Am 18.12.2015 9:08 vorm. schrieb "Raphael Das Gupta" <
notifications@github.com>:

**Comment by das-g** [comment]
status for `master`, too: PR #340

**Pull request merged**
