### PR TITLE
Feature/favicon and improve appereance

### LINKED ISSUE #131: Style the login page using bootstrap as well
Since we are using bootstrap, we should use it more consistently on the login page.

### LINKED ISSUE #232: Enhancements of visual appereance
- [x] In header add Logo "HSR" to the right (HSR Corporate Identity).
- [x] Enhance/replace "Pi" icon for „Login/Logout“ to make it more recognizable.
- [x] Check and eventually change (blue) colors in whole CSS according to color palette of HSR Corporate Identity.

### LINKED ISSUE #252: Website: Favicon and IE compatibility
- [x] Add Favicon (png can have any name).

    Icon that will be displayed in the browser tabs: 
    ```html
    <link rel="icon" type="image/png" href="favicon.png"/>
    ```
- [x] Add meta tag to ask Internet Explorer to behave:

    Sometimes a current IE version is installed, but system settings force it to use legacy document modes. Add following line to your head to make IE use the most current available mode: 
    ```html
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    ```

### PR DESCRIPTION
**Pull request by wasabideveloper**
Implementation of features #131, #252 and #232  (Merge will close #131, close #252 and close #232 ).

* tested views by hand:
  * /
  * /login
  * /orders/new [get/post]
  * /orders/{id}

To be reviewed by:
- [x] @das-g 
- [x] @hixi 

screen shot 2015-12-04 at 14 57 53
<hr />
screen shot 2015-12-04 at 14 58 07
<hr />
screen shot 2015-12-04 at 14 57 19
<hr />
screen shot 2015-12-04 at 14 57 41

### CODE REVIEW

**Comment by hixi** [comment]
Is the (written out) `Osmaxx` now redundant with the logo left thereof?

**Comment by wasabideveloper** [comment]
I don't think so because the logo is not so clear readable.

**Comment by wasabideveloper** [comment]
:heavy_check_mark:  We discussed it and I removed it.

**Comment by hixi** [comment]
:+1:

**Pull request merged**
